#自动合并coolsnowwolf/lede的源码到此仓库
name: Update Checker

#基础
on:
#主动触发
  workflow_dispatch:
#当有新推送到Master分支时触发
#   push:
#     branches: 
#       - master
# #每天晚上7点半自动合并源码
#   schedule:
#     - cron: 30 19 * * *

#工作流
jobs:

#合并
  merge:
    runs-on: ubuntu-latest
    steps:

#检出当前仓库
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

#设置GIT默认参数
    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

#拉取Lede仓库
    - name: Load upstream commits
      run: git pull https://github.com/coolsnowwolf/lede.git --log --no-commit

#应用提交
    - name: Apply commit changes
      id: applycommit
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        echo "::set-output name=status::update"
        else
        echo "There is no merge commits."
        echo "::set-output name=status::noupdate"
        fi

#推送提交
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH

#触发编译流
    - name: Trigger build
      if: steps.applycommit.outputs.status == 'update'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Build OpenWrt For N1